issue #9 buildsys: add ability to generate install cd

diff --git a/buildsys-internal b/buildsys-internal
--- a/buildsys-internal
+++ b/buildsys-internal
@@ -583,6 +583,7 @@ tar_pkgs()
 
 iso_pkgs()
 {
+	local i
 	ISO_ROOT=$DEV_ROOT/ISOROOT
 	install_pkgs
 	bs_notice "Cleaning $ISO_ROOT"
@@ -598,40 +599,52 @@ iso_pkgs()
 	install_pkgs
 
 	pushd $ISO_ROOT
-	rm -rvf fake
-	mkdir -vp fake/{needwrite,ramdisk}
-	mv -v etc/ var/ root/ home/ fake/needwrite/
-	ln -vfs fake/needwrite/etc etc
-	ln -vfs fake/needwrite/var var
-	ln -vfs fake/needwrite/root root
-	ln -vfs fake/needwrite/home home
 	cat > etc/rc.d/init.d/create_ramdisk <<- "EOF"
 	#!/bin/sh
-
-	dev_ram=/dev/ram0
+	# SET UP SOME VARIABLES FOR DEVICES AND DIRECTORIES
+	dev_ram=/dev/ram1
+	dev_ram2=/dev/ram2
 	dir_ramdisk=/fake/ramdisk
 	dir_needwrite=/fake/needwrite
-
+	# SOURCE THE FUNCTIONS FILE
 	source /etc/rc.d/init.d/functions
-
 	case "$1" in
 		start)
-			echo -n "Creating ext2fs on $dev_ram ...              "
+			# CREATE THE RAM DISK
+			echo "Creating ext2fs on $dev_ram..."
 			/sbin/mke2fs -m 0 -i 1024 -q $dev_ram > /dev/null 2>&1
 			evaluate_retval
 			sleep 1
-			echo -n "Mounting ramdisk on $dir_ramdisk ...         "
-			mount -n $dev_ram $dir_ramdisk
+			# MOUNT THE RAM DISK
+			echo "Mounting ramdisk on $dir_ramdisk..."
+			mount -n $dev_ram $dir_ramdisk -t ext2
 			evaluate_retval
 			sleep 1
-			echo -n "Copying files to ramdisk ...                 "
-			cp -dpR $dir_needwrite/* $dir_ramdisk > /dev/null 2>&1
+			# COPY FILES TO THE RAM DISK
+			echo "Copying files to ramdisk..."
+			cp -a $dir_needwrite/* $dir_ramdisk > /dev/null 2>&1
 			evaluate_retval
 			sleep 1
-			echo -n "Remount ramdisk to $dir_needwrite ...        "
+			# CREATE SECOND RAMDISK
+			echo "Creating second ramdisk"
+			/sbin/mke2fs -m 0 -i 1024 -q $dev_ram2 > /dev/null 2>&1
+			evaluate_retval
+			sleep 1
+			# MOUNT SECOND RAMDISK
+			echo "Mounting second ram disk"
+			mount -n $dev_ram2 $dir_needwrite -t ext2
+			evaluate_retval
+			sleep 1
+			# COPY FILES TO THE SECOND RAMDISK
+			echo "Copying files to the second ram disk"
+			cp -a $dir_ramdisk/* $dir_needwrite
+			evaluate_retval
+			sleep 1
+			# UNMOUNT THE FIRST RAMDISK
+			echo "Unmounting and clearing first ram disk"
 			umount -n $dir_ramdisk > /dev/null 2>&1
-			sleep 1
-			mount -n $dev_ram $dir_needwrite
+			blockdev --flushbufs /dev/ram1
+			evaluate_retval
 			sleep 1
 			;;
 		*)
@@ -640,9 +653,9 @@ iso_pkgs()
 			;;
 	esac
 	EOF
+
 	chmod -v 0755 etc/rc.d/init.d/create_ramdisk
-	mkdir -vp etc/rc.d/rcsysinit.d
-	ln -vfs ../init.d/create_ramdisk etc/rc.d/rcsysinit.d/S00create_ramdisk
+	ln -vfs ../init.d/create_ramdisk etc/rc.d/rcS.d/S00create_ramdisk
 
 	cat > etc/fstab <<- "EOF"
 	# Begin /etc/fstab for a bootable CD
@@ -651,19 +664,38 @@ iso_pkgs()
 	#                                                        order
 	#/dev/EDITME     /            EDITME  defaults        1     1
 	#/dev/EDITME     swap         swap   pri=1           0     0
-	proc           /proc        proc   defaults        0     0
-	sysfs          /sys         sysfs  defaults        0     0
+	proc           /proc        proc   nosuid,noexec,nodev        0     0
+	sysfs          /sys         sysfs  nosuid,noexec,nodev        0     0
+	devtmpfs          /dev         devtmpfs  mode=0755,nosuid        0     0
 	devpts         /dev/pts     devpts gid=4,mode=620  0     0
 	tmpfs          /dev/shm     tmpfs  defaults        0     0
 	tmp            /tmp         tmpfs  defaults        0     0
+	run            /run         tmpfs  defaults        0     0
 	# End /etc/fstab
 	EOF
 
-	rm -vf etc/rc.d/rcsysinit.d/S30checkfs
-	sed -i -e 's/remount//g' etc/rc.d/init.d/mountfs
+	rm -vf etc/rc.d/rcS.d/S30checkfs
+	rm -vf etc/rc.d/rcS.d/S40mountfs
+	#sed -i -e 's/.* remount.*/bash/g' -e 's/.*mount -f \/ *|| failed=1//g' etc/rc.d/init.d/mountfs
 	mknod lib/udev/devices/loop0 b 7 0
 	mkdir -pv dev
-	mknod dev/ram0 b 1 0
+	for i in 1 2; do
+		mknod dev/ram$i b 1 $i
+	done
+	mknod dev/null    c  1  3
+	mknod dev/zero    c  1  5
+	mknod dev/console c  5  1
+	mknod dev/ttyS0   c  4 64
+
+	rm -rvf fake
+	mkdir -vp fake/{needwrite,ramdisk}
+	mv -vf etc/ var/ root/ home/ dev/ fake/needwrite/
+	ln -vfs fake/needwrite/etc etc
+	ln -vfs fake/needwrite/var var
+	ln -vfs fake/needwrite/root root
+	ln -vfs fake/needwrite/home home
+	ln -vfs fake/needwrite/dev dev
+
 	dd if=/dev/zero of=boot/initrd bs=1k count=1 seek=8191
 	mke2fs -v -m 0 -i 1024 -F boot/initrd
 	mount -vo loop boot/initrd mnt
@@ -685,7 +717,7 @@ iso_pkgs()
 	mknod dev/hdc     b  22  0
 	mknod dev/hdd     b  22 64
 	mknod dev/hde     b  33  0
-	cp -v $ISO_ROOT/bin/{bash,mount,grep,umount,echo,dd} bin/
+	cp -v $ISO_ROOT/bin/{bash,mount,grep,umount,echo,dd,ls} bin/
 	cp -v $ISO_ROOT/usr/bin/test bin/
 	cp -v $ISO_ROOT/usr/sbin/chroot bin/
 	cp -v $ISO_ROOT/sbin/pivot_root bin/
@@ -798,12 +830,11 @@ iso_pkgs()
 
 	else
 
-		echo "Booting from $CDROM_DEVICE ...                  "
+		echo "Booting from $CDROM_DEVICE ..."
 
 		mount -n -o ro -t iso9660 $CDROM_DEVICE $TMP_MOUNT
 	fi
 	cd $TMP_MOUNT
-	exec bash
 	pivot_root . mnt
 	umount -n /mnt/proc
 	exec chroot . sh -c 'umount -n /mnt >/dev/null 2>&1;\
